// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUgqvrIEza9fPdnZNecohvqlj08XFOz7o',
    appId: '1:597809032936:web:0e0a8c85e58003d020e35d',
    messagingSenderId: '597809032936',
    projectId: 'multi-store-90b0d',
    authDomain: 'multi-store-90b0d.firebaseapp.com',
    storageBucket: 'multi-store-90b0d.appspot.com',
    measurementId: 'G-L2KT7X57M3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeJHxBxmqnkE2QsuayevI26c6BUAfbk0k',
    appId: '1:597809032936:android:a37c360e17619b4220e35d',
    messagingSenderId: '597809032936',
    projectId: 'multi-store-90b0d',
    storageBucket: 'multi-store-90b0d.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUgqvrIEza9fPdnZNecohvqlj08XFOz7o',
    appId: '1:597809032936:web:76c1949623f17c5620e35d',
    messagingSenderId: '597809032936',
    projectId: 'multi-store-90b0d',
    authDomain: 'multi-store-90b0d.firebaseapp.com',
    storageBucket: 'multi-store-90b0d.appspot.com',
    measurementId: 'G-D4DE6C430E',
  );
}
