// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeJHxBxmqnkE2QsuayevI26c6BUAfbk0k',
    appId: '1:597809032936:android:79b353a86cddf7e620e35d',
    messagingSenderId: '597809032936',
    projectId: 'multi-store-90b0d',
    storageBucket: 'multi-store-90b0d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUJEeRgbhymNOgyQjBMgumlfUJ7js1dSw',
    appId: '1:597809032936:ios:4fc1af5b3414d30720e35d',
    messagingSenderId: '597809032936',
    projectId: 'multi-store-90b0d',
    storageBucket: 'multi-store-90b0d.appspot.com',
    androidClientId: '597809032936-j7j1jls7hue8nmoro95ug66728vhi9iq.apps.googleusercontent.com',
    iosClientId: '597809032936-0m8qflk98rk2p30mbfgudmnc9bml8v9h.apps.googleusercontent.com',
    iosBundleId: 'com.example.supplierMultiStoreApp',
  );
}
